### ISSUE TITLE
Running inference notebook locally

### ISSUE THREAD

**Issue by PelopG** [spaceml-org/RaVAEn#1]
Hi,

I am trying to run the inference notebook locally on jupyter notebook.
At first I was experiencing problems with the creation of the environment from the env.yaml.
I was able to find a solution to that problem.

Now trying to run the inference notebook:
In this section found code below:
## Code
===== Parameters to adjust =====
Note: adjust these to where you downloaded the datasets and the pretrained models

event="floods" # change this accordingly to which dataset you downloaded
ID = "/datasets"
checkpoint="/pretrained/D_train_VAE_128small/3k0vhd2o/epoch_00-step_29653.ckpt"
dataset_root_folder = "/datasets/" + event

name="VAE_128small_DemoTest"

===== Parameters to keep the same ======

evaluation="vae_paper"
training="simple_vae"
module="deeper_vae"
plot_sequences="true"

========================================

!python3 -m scripts.evaluate_model \
    +dataset=floods_evaluation \
    ++dataset.root_folder=$dataset_root_folder \
    +training=$training \
    +normalisation=log_scale \
    +channels=high_res \
    +module=$module \
    +checkpoint=$checkpoint \
    +project="FDL21_RaVAEn_model_128small" \
    +evaluation=$evaluation \
    ++evaluation.plot_sequences=$plot_sequences \
    +name="{name}_{event}" \
    +dataset.test_overlap=[0,0] module.model_cls_args.latent_dim=128 module.model_cls_args.extra_depth_on_scale=0 module.model_cls_args.hidden_channels=[16,32,64] \
    ++evaluation.save_plots_locally=true \
    training.num_workers=2 training.batch_size_train=64 training.batch_size_valid=64 training.batch_size_test=64

    # the last few args set the same architecture as the one we used when training
    # and some hw specs settings:
    #training.num_workers=2 training.batch_size_train=64 training.batch_size_valid=64 training.batch_size_test=64

## Error experienced:
zsh:1: no matches found: +dataset.test_overlap=[0,0]

## Steps to reproduce the problem.
Running inference notebook locally

## Operating system
MacOS Ventura ; MacBook Pro M1 Pro - processor

**Comment by previtus** [comment]
Hello Pelop and thank you for your interest.
Hmm, I tried re-doing the steps on my side, just to check if some library version didn't change significantly, but I still was able to get it running (on Ubuntu 18.04.5 LTS).

Could you try running the same command inside the same environment, but outside of the jupyter notebook?
That would mean running something like what is in `eval_run_papers_v3_VAE_128_D_small.sh` after changing the paths. Something like this:

```
# Prep steps - I think you got these running already
git clone git@github.com:spaceml-org/RaVAEn.git
cd RaVAEn
make requirements
conda activate ravaen_env

```
Download the pretrained models and for example the floods dataset - and update the paths accordingly.

```
# Run the eval script
python3 -m scripts.evaluate_model +dataset=floods_evaluation ++dataset.root_folder="somewhere/datasets/floods" \
                +training=simple_vae \
                +normalisation=log_scale \
                +channels=high_res \
                +module=deeper_vae \
                +checkpoint="somewhere/pretrained/pretrained_small/D_train_VAE_128small/3k0vhd2o/checkpoints/epoch_00-step_29653.ckpt" \
                +project="eval_paper_VAE_128small" \
                +evaluation=vae_paper \
                ++evaluation.plot_sequences=true \
                +name="eval_paper_VAE_128small_flood" +dataset.test_overlap=[0,0] module.model_cls_args.latent_dim=128 module.model_cls_args.extra_depth_on_scale=0 module.model_cls_args.hidden_channels=[16,32,64]
```
Just to check if this would work outside of the notebook.

What comes to my mind with the error (_no matches found: +dataset.test_overlap=[0,0]_) is that sometimes different versions of hydra use and allow different syntax for the commands ...
Can I ask what are the versions of hydra and wandb you use? These were the ones I got with the default environment:

```
>>> print(hydra.__version__)
1.1.0
>>> print(wandb.__version__)
0.12.10
```

**Comment by PelopG** [comment]
Hello previtus,
Thank you for the reply.
I am have followed the steps you mention above.

I am getting this error after changing the _evaluation_model.py file_  "Example usage AE:"  found in the the scripts folder to the one mention above and implementing the required paths.

## Error Experienced 
```

Error executing job with overrides: []
Traceback (most recent call last):
  File "/Users/pelopidasgeorgiades/Desktop/DISSERATION/RaVAEn/scripts/evaluate_model.py", line 123, in main
    ParsedDataModule.load_or_create(cfg['dataset'], cfg['cache_dir'])
KeyError: 'dataset'

```

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

```
Error executing job with overrides: []
Traceback (most recent call last):
  File "/Users/pelopidasgeorgiades/Desktop/DISSERATION/RaVAEn/scripts/evaluate_model.py", line 419, in <module>
    main()
  File "/opt/miniconda3/envs/ravaen_env/lib/python3.9/site-packages/hydra/main.py", line 49, in decorated_main
    _run_hydra(
  File "/opt/miniconda3/envs/ravaen_env/lib/python3.9/site-packages/hydra/_internal/utils.py", line 367, in _run_hydra
    run_and_report(
  File "/opt/miniconda3/envs/ravaen_env/lib/python3.9/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/opt/miniconda3/envs/ravaen_env/lib/python3.9/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/opt/miniconda3/envs/ravaen_env/lib/python3.9/site-packages/hydra/_internal/utils.py", line 368, in <lambda>
    lambda: hydra.run(
  File "/opt/miniconda3/envs/ravaen_env/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 110, in run
    _ = ret.return_value
  File "/opt/miniconda3/envs/ravaen_env/lib/python3.9/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/opt/miniconda3/envs/ravaen_env/lib/python3.9/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "/Users/pelopidasgeorgiades/Desktop/DISSERATION/RaVAEn/scripts/evaluate_model.py", line 123, in main
    ParsedDataModule.load_or_create(cfg['dataset'], cfg['cache_dir'])
KeyError: 'dataset'
```

## Hydra and WandB versions
```
>>> print(hydra.__version__)
1.1.0
>>> print(wandb.__version__)
0.12.10
```

**Comment by PelopG** [comment]
Hi previtus,

I have changed the `eval_run_papers_v3_VAE_128_D_small.sh` file to your suggestion, but I am still experiencing an error

## Error
```
Error executing job with overrides: ['+dataset=floods_evaluation', '++dataset.root_folder=/RaVAEn/datasets/floods', '+training=simple_vae', '+normalisation=log_scale', '+channels=high_res', '+module=deeper_vae', '+checkpoint=RaVAEn/pretrained/pretrained_small/D_train_VAE_128small/3k0vhd2o/checkpoints/epoch_00-step_29653.ckpt', '+project=eval_paper_VAE_128small', '+evaluation=vae_paper', '++evaluation.plot_sequences=true', '+name=eval_paper_VAE_128small_flood', '+dataset.test_overlap=[0,0]', 'module.model_cls_args.latent_dim=128', 'module.model_cls_args.extra_depth_on_scale=0', 'module.model_cls_args.hidden_channels=[16,32,64]']
Traceback (most recent call last):
  File "/Users/pelopidasgeorgiades/Desktop/RaVAEn/scripts/evaluate_model.py", line 120, in main
    ParsedDataModule.load_or_create(cfg['dataset'], cfg['cache_dir'])
  File "/Users/pelopidasgeorgiades/Desktop/RaVAEn/src/data/datamodule.py", line 175, in load_or_create
    datamodule = ParsedDataModule(cfg)
  File "/Users/pelopidasgeorgiades/Desktop/RaVAEn/src/data/datamodule.py", line 30, in __init__
    self.train_ds = self.create_dataset(self.root_folder, self.train,
  File "/Users/pelopidasgeorgiades/Desktop/RaVAEn/src/data/datamodule.py", line 60, in create_dataset
    return MyConcatDataset(datasets)
  File "/Users/pelopidasgeorgiades/Desktop/RaVAEn/src/data/datamodule.py", line 217, in __init__
    super().__init__(datasets)
  File "/opt/miniconda3/envs/ravaen_env/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 238, in __init__
    assert len(datasets) > 0, 'datasets should not be an empty iterable'  # type: ignore[arg-type]
AssertionError: datasets should not be an empty iterable

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

```

My hydra and wandb versions:
```
>>> import hydra
>>> print(hydra.__version__)
1.1.0
>>> import wandb
>>> print(wandb.__version__)
0.12.10
```
I have tried changing the AssertionError to ignore[arg-type] but that didnt solve the issue.
Any ideas on how to solve this issue?

Regards,
Pelopidas

**Comment by previtus** [comment]
Hi Pelop,
Could you describe what exactly have you changed in the code? And what do you want to achieve with it - just rerunning our results, or making some alterations?
At the start, I'd recommend not making any changes with the code, before you are able to run the basic calls - then if these work, you can start editing it...

As for the error, the:
`assert len(datasets) > 0, 'datasets should not be an empty iterable'`
Is usually triggered when no data could be loaded. This happens for example if the **path to the dataset is not set up properly**. 

If you ran the code with the following override `'++dataset.root_folder=/RaVAEn/datasets/floods', ` - that's where the data should be.
Can you run `ls /RaVAEn/datasets/floods` and see files?
If you place the data let's say to `/home/<your username>/Downloads/floods` , you should set the same in the override: `'++dataset.root_folder=/home/<your username>/Downloads/floods', ` .

**Comment by PelopG** [comment]
Hi previtus,
I just want to re-run the current results and then make some modifications as part of my undergraduate dissertation project.

I have deleted the envrironment and created a new one using `make requirements`.


Please find the code below; modified file: `eval_run_papers_v3_VAE_128_D_small.sh`

```
# Runs evaluation on manually selected model checkpoint
#   (note: on different architecture layouts might need some extra args, ideally the same as the used training script)

# Run the eval script
python3 -m scripts.evaluate_model \
    +dataset=floods_evaluation \
    ++dataset.root_folder="../Downloads/floods" \
    +training=simple_vae \
    +normalisation=log_scale \
    +channels=rgb \
    +module=simple_ae_with_linear \
    +checkpoint="../Downloads/FDL21_RaVAEn_models/D_train_VAE_128small/3k0vhd2o/checkpoints/epoch_00-step_29653.ckpt" \
    +project="eval_paper_VAE_128small" \
    +evaluation=ae_base \
    ++evaluation.plot_sequences=true \
    +name="eval_paper_VAE_128small_flood" \
    +module.model_cls_args.hidden_channels=[16,32,64] \
    +module.model_cls_args.extra_depth_on_scale=0 \
    +dataset.test_overlap=[0,0] module.model_cls_args.latent_dim=128 
plot_sequences=true

###############
# VAEs
###############
evaluation=vae_paper
training=simple_vae
###############

checkpoint=/data/results/ex02_nips_vitek_trainings/D_train_VAE_128small/3k0vhd2o/checkpoints/epoch_00-step_29653.ckpt
module=deeper_vae
name=D_VAE_128small_3k0vhd2o_epoch0
```

Terminal respone to allocating the files:
```

(ravaen_env) pelopidasgeorgiades@Pelopidass-MacBook-Pro RaVAEn % ls ../Downloads/floods
EMSR260_02VIADANA	EMSR271_02FARKADONA	EMSR324_04LESPIGNAN	EMSR333_02PORTOPALO
(ravaen_env) pelopidasgeorgiades@Pelopidass-MacBook-Pro RaVAEn % ls ../Downloads/FDL21_RaVAEn_models/D_train_VAE_128small/3k0vhd2o/checkpoints
epoch_00-step_29653.ckpt

```

But I still experiencing the same error as before:

```
Error executing job with overrides: ['+dataset=floods_evaluation', '++dataset.root_folder=../Downloads/floods', '+training=simple_vae', '+normalisation=log_scale', '+channels=rgb', '+module=simple_ae_with_linear', '+checkpoint=../Downloads/FDL21_RaVAEn_models/D_train_VAE_128small/3k0vhd2o/checkpoints/epoch_00-step_29653.ckpt', '+project=eval_paper_VAE_128small', '+evaluation=ae_base', '++evaluation.plot_sequences=true', '+name=eval_paper_VAE_128small_flood', '+module.model_cls_args.hidden_channels=[16,32,64]', '+module.model_cls_args.extra_depth_on_scale=0', '+dataset.test_overlap=[0,0]', 'module.model_cls_args.latent_dim=128']
Traceback (most recent call last):
  File "/Users/pelopidasgeorgiades/RaVAEn/scripts/evaluate_model.py", line 121, in main
    ParsedDataModule.load_or_create(cfg['dataset'], cfg['cache_dir'])
  File "/Users/pelopidasgeorgiades/RaVAEn/src/data/datamodule.py", line 175, in load_or_create
    datamodule = ParsedDataModule(cfg)
  File "/Users/pelopidasgeorgiades/RaVAEn/src/data/datamodule.py", line 30, in __init__
    self.train_ds = self.create_dataset(self.root_folder, self.train,
  File "/Users/pelopidasgeorgiades/RaVAEn/src/data/datamodule.py", line 60, in create_dataset
    return MyConcatDataset(datasets)
  File "/Users/pelopidasgeorgiades/RaVAEn/src/data/datamodule.py", line 217, in __init__
    super().__init__(datasets)
  File "/opt/miniconda3/envs/ravaen_env/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 238, in __init__
    assert len(datasets) > 0, 'ignore[arg-type]'  # type: ignore[arg-type]
AssertionError: ignore[arg-type]

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
I have decided that it will be easier for me to run the code on google Colab which I have managed to execute the code.
Thank you very much for your time, to help me with the issue.
