### ISSUE TITLE
Issue with displaying UMAP

### ISSUE THREAD

**Issue by PelopG** [spaceml-org/RaVAEn#2]
Hi,
I have been trying to display the UMAP using:
```
# UMAP testing

!python3 -m scripts.eval_tsne \
  +training=simple_vae \
  +dataset=floods_evaluation \
  +module=deeper_vae \
  +project="Testing" \
  +normalisation=log_scale \
  +checkpoint="/content/pretrained/D_train_VAE_128small/3k0vhd2o/checkpoints/epoch_00-step_29653.ckpt"\
  +channels=rgb`

Taken from the `scripts/eval_tsne.py
```
**Error**
```
Error executing job with overrides: ['+training=simple_vae', '+dataset=floods_evaluation', '+module=deeper_vae', '+project=Testing', '+normalisation=log_scale', '+checkpoint=/content/pretrained/D_train_VAE_128small/3k0vhd2o/checkpoints/epoch_00-step_29653.ckpt', '+channels=rgb']
Traceback (most recent call last):
  File "/content/RaVAEn/scripts/eval_tsne.py", line 231, in main
    data_module = ParsedDataModule.load_or_create(cfg['dataset'], cfg['cache_dir'])
  File "/content/RaVAEn/src/data/datamodule.py", line 178, in load_or_create
    datamodule = ParsedDataModule(cfg)
  File "/content/RaVAEn/src/data/datamodule.py", line 30, in __init__
    self.train_ds = self.create_dataset(self.root_folder, self.train,
  File "/content/RaVAEn/src/data/datamodule.py", line 60, in create_dataset
    return MyConcatDataset(datasets)
  File "/content/RaVAEn/src/data/datamodule.py", line 217, in __init__
    super().__init__(datasets)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataset.py", line 238, in __init__
    assert len(datasets) > 0, 'datasets should not be an empty iterable'  # type: ignore[arg-type]
AssertionError: datasets should not be an empty iterable

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
I am running the code in google colab (inference), taken from the link available in the page.

Please let me know how to resolve this issue and if I need to provide further information.

**Comment by previtus** [comment]
Hi Pelop,
As this bit of code isn't in the /notebooks/ it is not meant for readily made live demos of this repo.
This being said, I have another, separate Colab notebook I could link that can demonstrate the runs with tSNE and UMAP - although it just loads some pre-saved latents and images.

Check the colab here: [https://colab.research.google.com/drive/1hZAwsZ8bWjwKFkI9ESvceYuLoVTsT8ni?usp=sharing](https://colab.research.google.com/drive/1hZAwsZ8bWjwKFkI9ESvceYuLoVTsT8ni?usp=sharing&authuser=0)

Alternatively, you could go ahead and directly use the prepared function ("visualize_embedding" from eval_tsne.py) with your own latents and images (saved from another model for example).

Hope this helps,
V
